config/routes.rb
Manderley::Application.routes.draw do
  devise_for :users
  resources :users, only: [:index, :edit, :show, :update]
  resources :adresses
  resources :movies do
    resources :comments, shallow: true

    get  :new_cast
    post :add_cast

    delete 'destroy_cast/:id', to: 'movies#destroy_cast'

    resources :casts, shallow: true
  end
  resources :people

  mount JasmineRails::Engine => "/specs" if defined?(JasmineRails)
  

  root 'movies#index'

  get 'users', to: 'users#index'
  get 'profile', to: 'users#profile', as: :profile

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, except: [:index, :new, :create]
  before_filter :authenticate_user!, except: [:index, :show]
  TweetWorker.perform_async(1, 1)
  def new_cast
    @people = @movie.people.all
    @cast = @movie.casts.build
  end

  def add_cast
    respond_to do |format|
        format.html { redirect_to @movie, notice: 'ADDDDDDDDDD.' }
    end
  end

  def destroy_cast
    @movie.casts.find(params[:id]).destroy
    respond_to do |format|
        format.html { redirect_to @movie, notice: 'Cast deleted.' }
    end
  end

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all
    respond_to do |format|
      format.html { render action: "index" }
      format.json { render action: 'index' }
    end
  end

  # GET /movies/1
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)
    @movie.user = current_user

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render action: 'show', status: :created, location: @movie }
      else
        format.html { render action: 'new' }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  #DELETE /movies/1
  #DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_path }
      format.json { head :no_content }
      format.js { render partial: 'destroy_animation', locals: {resource: @movie} }
    end
  end
  
  private

    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      params[:movie_id].present? ? @movie = Movie.friendly.find(params[:movie_id]) : @movie = Movie.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(
        :title,
        :duration,
        :synopsis,
        :year,
        {categories: []},
        :photo
      )
    end
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/movies/_cast_form.html.erb
<%= form_for([@movie, @cast], url: movie_add_cast_path(@movie)) do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cast.errors.count, "error") %> prohibited this cast from being saved:</h2>

      <ul>
      <% @cast.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
  <div class="field">
    <%= f.label :person_id %>
    <%= collection_select(:person, :person_id, @people.collect, :id, :name) %>
  </div>

  <div class="field">
    <%= f.label :role %>
    <select id="role" name="role">
      <option value="actor">Actor</option>
      <option value="director">Director</option>
      <option value="producer">Producer</option>
      <option value="staff">Staff</option>
    </select>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movies/_casts_table.html.erb
<table class="table table-striped">
  <thead>
      <tr>
        <th>Name</th>
        <th>Role</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @movie.casts.each do |cast| %>

          <%= content_tag_for(:tr, cast) do %>
            
            <td class="col-md-5">
              <%= cast.person_id %>
            </td>
            <td class="col-md-5">
              <%= cast.role %>
            </td>
            <td class="col-md-1"><%= link_to 'Edit', edit_person_path(cast), class: "btn btn-small btn-info sm-width" %>
            </td>
            
          <% end %>
          
      <% end %>
  </tbody>
<table>

app/views/movies/_comments_table.html.erb
<table class="table table-striped">
  <thead>
      <tr>
        <th>Comment</th>
        <th>Author</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @movie.comments.each do |comment| %>

          <%= content_tag_for(:tr, comment) do %>
            
            <td class="col-md-5">
              <%= comment.body %>
            </td>
            <td class="col-md-5">
              <%= comment.author %>
            </td>
            <td class="col-md-1"><%= link_to 'Edit', edit_comment_path(comment), class: "btn btn-small btn-info sm-width" %></td>
            <td class="col-md-1"><%= link_to 'Delete', comment, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-small btn-danger sm-width" %>
            </td>

          <% end %>

      <% end %>
    </tbody>
<table>

app/views/movies/_form.html.erb
<%= simple_form_for(@movie) do |f| %>
  <%= image_tag(@movie.photo_url) if @movie.photo? %>
  <%= f.input :photo %>
  <%#= f.input :photo_cache, :hidden %>
  <%= f.input :title %>
  <%= f.input :duration %>
  <%= f.input :synopsis %>
  <%= f.input :year %>
  <%= f.input :categories, collection: Movie::CATEGORIES, as: :check_boxes, label_method: lambda { |x| x.to_s.titleize} %>
  <%= f.submit %>
<% end %>

app/views/movies/_movies_table.html.erb
<td class="col-md-2"><%= movie.title %></td>
<td class="col-md-1"><%= movie.duration %></td>
<td class="col-md-2"><%= movie.synopsis %></td>
<td class="col-md-1"><%= movie.year %></td>
<td class="col-md-1"><%= movie.categories %></td>
<td class="col-md-1"><%= movie.user.email%></td>
<td class="col-md-1"><%= link_to 'Show', movie, class: "btn btn-small btn-success sm-width" %></td>

<td class="col-md-1">
  <% if user_signed_in? %>
    <%= link_to 'Edit', edit_movie_path(movie), class: "btn btn-small btn-info sm-width" %>
      <% end %>
  </td>
<td class="col-md-1">
  <% if user_signed_in? %>
    <% if current_user==movie.user %>
      <%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-small btn-danger sm-width movie-destroy", remote: true %>
    <% end %>
  <% end %>
</td>

app/views/movies/_movies_table_layout.html.erb
<tr>
  <%= yield %>
</tr>

app/views/movies/_people_table.html.erb
<table class="table table-striped">
  <thead>
      <tr>
        <th>Name</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @movie.people.each do |person| %>

          <tr>
            <td class="col-md-5">
              <%= person.Name %>
            </td>

            <td class="col-md-1"><%= link_to 'Edit', edit_person_path(person), class: "btn btn-small btn-info sm-width" %></td>
            <td class="col-md-1"><%= link_to 'Delete', person, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-small btn-danger sm-width" %>
            </td>
          </tr>
      <% end %>
  </tbody>
<table>

app/views/movies/edit.html.erb
<h1>Editing movie</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<%= t(:hello) %>

<h1>Listing movies</h1>

<%= link_to 'New Movie', new_movie_path, class: "btn btn-small btn-success" %>
<style>img{max-height: 80px; max-width: 80px;}</style>
<table class="table table-striped">
  <thead>
    <tr>
      <th> </th>
      <th>Title</th>
      <th>Duration</th>
      <th>Synopsis</th>
      <th>Year</th>
      <th>Categories</th>
      <th>Owner</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <style>.odd{background-color: #ddd;} .even{background-color: white;}</style>
  <tbody>
    <% @movies.each do |movie| %>
      <tr id="movie_<%= movie.id %>" class="movie">
        <td class="col-md-1"><%= image_tag(movie.photo_url) if movie.photo? %></td>
        <td class="col-md-1"><%= movie.title %></td>
        <td class="col-md-1"><%= movie.duration %></td>
        <td class="col-md-2"><%= movie.synopsis %></td>
        <td class="col-md-1"><%= movie.year %></td>
        <td class="col-md-1"><%= movie.categories %></td>
        <td class="col-md-1"><%= movie.user.email%></td>
        <td class="col-md-1"><%= link_to 'Show', movie, class: "btn btn-small btn-success sm-width" %></td>
        
        <td class="col-md-1">
          <% if user_signed_in? %>
            <%= link_to 'Edit', edit_movie_path(movie), class: "btn btn-small btn-info sm-width" %>
              <% end %>
          </td>
        <td class="col-md-1">
          <% if user_signed_in? %>
            <% if current_user==movie.user %>
              <%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-small btn-danger sm-width", remote: true %>
            <% end %>
          <% end %>
        </td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/movies/new.html.erb
<h1>New movie</h1>

<%= render 'form' %>

<%= link_to 'Back', movies_path %>

app/views/movies/new_cast.html.erb
<h1>New Cast</h1>

<%= render 'cast_form' %>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Movie info: </h1>
<%= image_tag(@movie.photo_url) if @movie.photo? %>
<p>
  <strong>Title:</strong>
  <%= @movie.title %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @movie.duration %>
</p>

<p>
  <strong>Synopsis:</strong>
  <%= @movie.synopsis %>
</p>

<p>
  <strong>Year:</strong>
  <%= @movie.year %>
</p>

<p>
  <strong>Categories:</strong>
  <%= @movie.categories %>
</p>

<%= link_to 'Edit', edit_movie_path(@movie), class: "btn btn-small btn-info" %>
<%= link_to 'Back', movies_path, class: "btn btn-small btn-info" %>
<!-- <p>
  <h2>People:</h2>
  
  <<!--%= render 'people_table' %>

<<!--%= link_to 'New person', new_person_path(@movie[:id]), class: "btn btn-small btn-success" %>

</p> -->
<p>
  <h2>Casts:</h2>
  
  <%= render 'casts_table' %>

<%= link_to 'New Cast', movie_new_cast_path(@movie), class: "btn btn-small btn-success" %>

</p>
<p>
  <h2>Comments:</h2>
  
  <%= render 'comments_table' %>

<%= link_to 'New Comment', new_movie_comment_path(@movie[:id]), class: "btn btn-small btn-success" %>

</p>