config/routes.rb
Manderley::Application.routes.draw do
  devise_for :users
  resources :users, only: [:index, :edit, :show, :update]
  resources :adresses
  resources :movies do
    resources :comments, shallow: true

    get  :new_cast
    post :add_cast

    delete 'destroy_cast/:id', to: 'movies#destroy_cast'

    resources :casts, shallow: true
  end
  resources :people

  mount JasmineRails::Engine => "/specs" if defined?(JasmineRails)
  

  root 'movies#index'

  get 'users', to: 'users#index'
  get 'profile', to: 'users#profile', as: :profile

end

app/models/user.rb
class User < ActiveRecord::Base
  
  rolify
  
  include Authority::UserAbilities
  include Authority::Abilities
  # self.authorizer_name = 'UserAuthorizer'

  has_many :movies
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :async,
         :recoverable, :rememberable, :trackable, :validatable

  def admin
    self.has_role? :admin
  end
  alias_method :admin?, :admin

  def admin= value
    if value == "1"
      self.add_role :admin
    else
      self.remove_role :admin
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :show, :update]
  before_filter :authenticate_user!, onlu: [:edit, :update]

  def index
    @users = User.all
  end

  def show
  end

  def profile
    @user = current_user
    render 'show'
  end

  def edit
  end

  def update
    authorize_action_for @user
    # if current_user.has_role? :admin
      if @user.update(user_params)
        redirect_to @user, notice: 'User was successfully updated.'
      else
        render 'edit'
      end
    # else
    #   render 'show'
    # end
  end

  protected

  def set_user
    @user = User.find params[:id]
  end

  def user_params
    params.require(:user).permit(:admin)
  end

end

app/views/users/edit.html.erb
<%= simple_form_for @user do |f| %>
  <%# if current_user.has_role :admin %>
    <%= f.input :admin, as: :boolean %>
    <%= f.submit %>
  <%# else %>
    <%# redirect_to @user %>
  <%# end %>
<% end %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table class="table"> <!-- table-striped -->
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <style>.odd{background-color: #ddd;} .even{background-color: white;}</style>
  <tbody>
    <% @users.each do |user| %>
      <tr class="<%= cycle("odd", "even") -%>">
        <td class="col-md-2"><%= user.email %></td>
        <td class="col-md-1"></td>
        <td class="col-md-2"></td>
        <td class="col-md-1"></td>
        <td class="col-md-1"></td>
        <td class="col-md-1"></td>
        <td class="col-md-1">
          <% if user_signed_in? %>
            <% if current_user.has_role? :admin %>
              <%= link_to 'Edit', edit_user_path(user), class: "btn btn-small btn-info sm-width" %>
            <% end %>
          <% end %>
        </td>
        
        <td class="col-md-1">
              <%= link_to 'Show', user, class: "btn btn-small btn-info sm-width" %>
        </td>
        <td class="col-md-1">
              <%#= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-small btn-danger sm-width" %>
        </td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/users/show.html.erb
<%= @user.email %>
<br>
<%= @user.admin ? "Admin" : "Regular user" %>
<br>

<%= link_to 'Edit', edit_user_path(@user), class: "btn btn-small btn-info" %>
<%= link_to 'Back', users_path, class: "btn btn-small btn-info" %>